language: scala
scala:
- 2.11.5
jdk:
- oraclejdk7
#branches:
#  only:
#  - master
notifications:
  email:
    recipients:
    - charles.kubicek@digital.hmrc.gov.uk
#after_success:
#- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'