language: scala
scala:
- 2.10.4
jdk:
- oraclejdk7
#branches:
#  only:
#  - master
notifications:
  email:
    recipients:
    - charles.kubicek@digital.hmrc.gov.uk
    on_success: change
    on_failure: always
#after_success:
#- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
